### ISSUE TITLE
What if I want to put index.html, etc. into the src/ directory?

### ISSUE THREAD

**Issue by surferjeff** [chriscalo/vite-multipage#2]
I want index.html and all my source files to live in a /src directory.

When I try, they end up at dist/src/index.html.  I want them to end up at dist/index.html.

**Comment by chriscalo** [comment]
Hi, @surferjeff, it's been a lil while since I've looked at this code, but here's my guess from a quick peek at the Vite docs:

In `vite.config.js`, specify `root: ./src` so that Vite knows the `src` directory is where your root `index.html` file lives. I think this should fix the problem of files ending up at `dist/src/` when you want them at `dist/`, but I haven't tried it. See https://vitejs.dev/config/shared-options.html#root.

**Comment by surferjeff** [comment]
I'll give that a try.  Thanks!
